---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users-secret
  namespace: pacman
type: Opaque
data:
  database-admin-name: Y2x5ZGU=
  database-admin-password: Y2x5ZGU=
  database-name: cGFjbWFu
  database-password: cGlua3k=
  database-user: Ymxpbmt5
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-users-secret
  namespace: pacman
type: Opaque
stringData:
  aws-access-key-id: CHANGE_THIS
  aws-secret-access-key: CHANGE_THIS
---
